### ISSUE TITLE
[Reqeust] Help I need standalone sharecode generator

### ISSUE THREAD

**Issue by lilgandhi1199** [jakoch/csgo-cli#7]
Help! I think the sharecode must be inside this demo info file too somehow.
Is the title simply all we need for the 3 variables?
match730_
003131049693715365895_ <<< Match ID
1959052661_ <<< Reservation ID
111.dem <<< Port #

Are these the 3 variables you are referring to in your function
string toDemoShareCode(uint64_t matchid, uint64_t reservationid, uint32_t tvport)

I have been collecting my demos and providing a community service of analyzing everyone's statistics just like csgostats.gg but then I make up a few MVP awards related to those and post the picture on my profile and tag every player's steam ID in it so they get alerted in their steam section.
Take a look at my profile you'll see I've downloaded and done this for the past 270+ games
https://steamcommunity.com/profiles/76561197997327350/

Anyways I think everyone is afraid to click on the link although it's simply a direct link (that csgo ends up navigating to) through those sharecodes... for example for the one above it goes like this
match730_003379593509047632119_0076099213_128
turns into
replay128.valve.net/730/003379593509047632119_0076099213.dem.bz2

Now I think if instead I provided the match sharecodes in every tagged screenshot people might actually trust it/wouldn't have to fuddle around with unzipping the bz2 file and running console commands. However as it is now I've written a script for every part of the journey from demo file to screenshot > caption (which is the description to each photo it's own relevant valve server link)
It seems like you've cracked the code on how that's done. Could you compile a standalone exe that I input the demo info file or the demo file or just that demo name (which has all 3 variables you need?) and then it dumps the sharecode into a text file. I can write a script to feed it one at a time. I'm sure the variables would be inside of the demo info file itself too since even if you fail to finish downloading a demo it will display all the kills deaths and give you a proper download share code link too. Can you give me an example of those 3 variables if I have it wrong and their lengths? and the output? I'd rather keep it automated or I'll probably stop doing this if I have to start manually doing things. Please Help!

**Comment by jakoch** [comment]
Hey!

I don't know, if i can help you with your project. Let's see.. 

Maybe you can understand the sharecode calculation a bit better by looking at the old version of it:

https://github.com/jakoch/csgo-cli/blob/704e15fb8212b321638afa9e598f67e7bbea8993/src/ShareCode.h#L26-L55

> Can you give me an example of those 3 variables if I have it wrong and their lengths? and the output?

Like described, i'm taking the values for the sharecode calculation from the protobuf data (CMsgGCCStrike15_v2_MatchList)

https://github.com/jakoch/csgo-cli/blob/2f8a0f3ccd7e0ee8109a31ce89aa805478684d29/src/CSGOMatchList.cpp

and use the calculator to get the sharecode

https://github.com/jakoch/csgo-cli/blob/2f8a0f3ccd7e0ee8109a31ce89aa805478684d29/src/main.cpp#L357-L358

And of course, you can do it in reverse (also with example values for testing):

https://github.com/jakoch/csgo-cli/blob/704e15fb8212b321638afa9e598f67e7bbea8993/src/ShareCode.h#L154-L159

Does this help you? Feel free to ask more questions... 

----

Would it help you, if my tool would actually download the demos?
For instance, download all recent match demos, skip if already downloaded, into a local folder.
So that you can process the demo file (extract, read, do your stats calc, generate images or stats table etc)?

Would it help you, if my tool would do some stats calculations for a specific match?
I have a section prepared for that, but it's commented out.
I didn't work on it, because of two reasons. Firstly, csgostats.gg does a great job, so why do it locally?
Secondly, i wanted to keep complexity of the tool low, because stats calculation tend to get out of hand quickly and often require a little database to keep track of names and numbers, before a final report can be generated.

**Comment by lilgandhi1199** [comment]
Ah okay I saw those 3 entries and was hoping they weren't it. I have no idea how to get that information with the tools I'm already using I don't think but I mostly automated it a little bit already. I could do something inside CSGO with grabbing the clipboard once it's filled but someone has already developed "CSGO Demos Manager" which downloads demos and grabs all the data out of them including that sharecode I just didn't see the option before. And Then I dump his data and parse it out from there. He's on github too but don't worry about me. I can mark it as sharecode saved with nice colors in his gui so that's actually easier to track anyways before I do a batch of 70 demos and upload them and mark it a different color. I am happy for now but I might be back to bug you some more soon incase I do need your help with something you seem like a helpful person. Thank You!

**Comment by jakoch** [comment]
Ok. Happy hacking on your project then. 
Feel free to ask... i will then reopen, closing for now.
